name = "AI-Uveso"
uid = "62e2j64a-AIUV-108-89465-146as555a8u3"
version = 108
copyright = "2017-2022 Uveso"
description = "(For FAF only) Advanced turtle AI. Supports Nomads and other unit mods"
author = "Uveso"
url = "https://forum.faforever.com/topic/350/"
icon = "/mods/AI-Uveso/UvesoAI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
