name = "AI-Uveso"
uid = "62e2j64a-AIUV-0710-89465-146as555a8u3"
version = 71
copyright = "Uveso 2017-2019"
description = "(For FAF only)"
author = "Uveso"
url = ""
icon = "/mods/AI-Uveso/UvesoAI.jpg"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
