
Uveso_0001="AI: Uveso Adaptive"
Uveso_0002="A balanced AI. Good for 5x5, 10x10 and 20x20 maps."
Uveso_0003="AIx: Uveso Adaptive"
Uveso_0004="A balanced AI using cheat options. Good for 5x5, 10x10 and 20x20 maps."

Uveso_0005="AI: Uveso Rush"
Uveso_0006="A rushing AI. Good for 5x5 and 10x10 maps."
Uveso_0007="AIx: Uveso Rush"
Uveso_0008="A rushing AI using cheat options. Good for 5x5 and 10x10 maps."

Uveso_0009="AI: Uveso Experimentals"
Uveso_0010="A experimental AI. Good for 10x10 and 20x20 maps."
Uveso_0011="AIx: Uveso Experimentals"
Uveso_0012="A experimental AI using cheat options. Good for 10x10 and 20x20 maps."

Uveso_0017="AIx: Uveso Overwhelm"
Uveso_0018="A cheating AI with variable buildfactor, that start to overwhelm the enemy after 20 minutes. Good for 5x5, 10x10 and 20x20 maps."

Uveso_0013="AI: Uveso Easy"
Uveso_0014="An easy AI. Good for 5x5, 10x10 and 20x20 maps."
Uveso_0015="AIx: Uveso Easy"
Uveso_0016="A easy AI using cheat options. Good for 5x5, 10x10 and 20x20 maps."

aisettingsUveso_0153="DEBUG: AI pathfinding"
aisettingsUveso_0154="Displays pathfinding, waypoints and location radii (only AI-Uveso)"
aisettingsUveso_0155="Off"
aisettingsUveso_0156="Display is off"
aisettingsUveso_0185="Pathfinding"
aisettingsUveso_0186="Show pathfinding for all layers"
aisettingsUveso_0157="Pathfinding and locations"
aisettingsUveso_0158="Show pathfinding and location radii"
aisettingsUveso_0204="Pathfinding and marker threat"
aisettingsUveso_0205="Show pathfinding and threats saved in AI markers"
aisettingsUveso_0209="Pathfinding and IMap threat"
aisettingsUveso_0210="Show pathfinding and threats from ingame threatmap"
aisettingsUveso_0159="Path and land marker"
aisettingsUveso_0160="Show pathfinding, land waypoints and paths"
aisettingsUveso_0161="Path and water marker"
aisettingsUveso_0162="Show pathfinding, water waypoints and paths"
aisettingsUveso_0163="Path and amphibious marker"
aisettingsUveso_0164="Show pathfinding, amphibious waypoints and paths"
aisettingsUveso_0165="Path and air marker"
aisettingsUveso_0166="Show pathfinding, air waypoints and paths"

aisettingsUveso_0167="DEBUG: AI Platoon names"
aisettingsUveso_0168="Displays Platoon and AI plan name"
aisettingsUveso_0169="Display is off"
aisettingsUveso_0170="AI Uveso names"
aisettingsUveso_0171="Show platoon and AI plan name for AI Uveso"
aisettingsUveso_0206="AI RNG names"
aisettingsUveso_0207="Show platoon and AI plan name for AI RNG"
aisettingsUveso_0219="AI NutCracker names"
aisettingsUveso_0220="Show platoon and AI plan name for AI NutCracker"
aisettingsUveso_0216="AI Swarm names"
aisettingsUveso_0217="Show platoon and AI plan name for AI Swarm"
aisettingsUveso_0172="AI Dilli names"
aisettingsUveso_0173="Show platoon and AI plan name for AI Dilli"
aisettingsUveso_0174="AI Sorian names"
aisettingsUveso_0175="Show platoon and AI plan name for AI Sorian"
aisettingsUveso_0176="All AI's"
aisettingsUveso_0177="Show platoon and AI plan name for all AI's"

aisettingsUveso_0178="DEBUG: AI BuilderManager"
aisettingsUveso_0179="Print platoon builder names into the game.log"
aisettingsUveso_0180="Logging is off"
aisettingsUveso_0181="Log builder for AI Uveso"
aisettingsUveso_0208="Log builder for AI RNG"
aisettingsUveso_0221="Log builder for AI NutCracker"
aisettingsUveso_0182="Log builder for AI Dilli"
aisettingsUveso_0218="Log builder for AI Swarm"
aisettingsUveso_0183="Log builder for AI Sorian"
aisettingsUveso_0184="Log builder for all AI's"

aisettingsUveso_0211="DEBUG: Endless game loop"
aisettingsUveso_0212="Running the game in an endless loop for long time testing"
aisettingsUveso_0213="On"
aisettingsUveso_0214="Endless play off"
aisettingsUveso_0215="Endless play on"

aisettingsUveso_0187="AI Unit Cap"
aisettingsUveso_0188="Set an AI unit cap independently from player unit cap."
aisettingsUveso_0189="%s units per AI may be in play"
aisettingsUveso_0190="Same as Player Cap"
aisettingsUveso_0191="AI uses settings from player unit cap."

aisettingsUveso_0192="AI Map Marker generator"
aisettingsUveso_0193="Autogenerate map markers for AI pathfinding on 5x5 and 10x10 maps"
aisettingsUveso_0194="Original Map markers"
aisettingsUveso_0195="Use map markers done by the mapauthor"
aisettingsUveso_0196="Autogenerate when needed"
aisettingsUveso_0197="Autogenerate map markers if no original markers are present"
aisettingsUveso_0198="Autogenerate Always"
aisettingsUveso_0199="Autogenerate map markers always (ignore original markers if present)"
aisettingsUveso_0200="No Marker"
aisettingsUveso_0201="Use the c-engine to path the way (20%% slower)"
aisettingsUveso_0202="Print to game.log"
aisettingsUveso_0203="Print the marker masterchain to the game.log for copy&paste"

aisettingsUveso_0222="AIx Overwhelm cheat increase"
aisettingsUveso_0223="Set the cheat multiplier increase for the AIx Overwhelm. The multiplier is increased every minute with this value"

aisettingsUveso_0224="AIx Overwhelm start time"
aisettingsUveso_0225="Set the delay in minutes before the AIx Overwhelm starts to increase the cheat multiplier"
