
Uveso_0001="KI: Uveso Adaptiv"
Uveso_0002="Eine ausbalancierte KI. Gut für 5x5, 10x10 und 20x20 Karten."
Uveso_0003="KIx: Uveso Adaptiv"
Uveso_0004="Eine ausbalancierte KI, Einstellbar über Cheat-Optionen. Gut für 5x5, 10x10 und 20x20 Karten."

Uveso_0005="KI: Uveso Sturm"
Uveso_0006="Eine Sturm KI. Gut für 5x5 und 10x10 Karten."
Uveso_0007="KIx: Uveso Sturm"
Uveso_0008="Eine Sturm KI, Einstellbar über Cheat-Optionen. Gut für 5x5 und 10x10 Karten."

Uveso_0009="KI: Uveso Experimentals"
Uveso_0010="Eine KI die auf Experimentals fokussiert ist. Gut für 10x10 und 20x20 Karten."
Uveso_0011="KIx: Uveso Experimentals"
Uveso_0012="Eine KI die auf Experimentals fokussiert ist, Einstellbar über Cheat-Optionen. Gut für 10x10 und 20x20 Karten."

Uveso_0017="AIx: Uveso Brecher"
Uveso_0018="Eine KI die ab der 20. Minute mit erhöhter Baugeschwindikeiten arbeitet. Gut für 5x5, 10x10 und 20x20 maps."

Uveso_0013="KI: Uveso Einfach"
Uveso_0014="Eine einfache KI. Gut für 5x5, 10x10 und 20x20 Karten"
Uveso_0015="KIx: Uveso Einfach"
Uveso_0016="Eine einfache KI, Einstellbar über Cheat-Optionen. Gut für 5x5, 10x10 und 20x20 Karten"

aisettingsUveso_0153="DEBUG: KI Wegfindung"
aisettingsUveso_0154="Zeigt Wegfindung, Wegpunkte und Standort Radien (nur KI-Uveso)"
aisettingsUveso_0155="Aus"
aisettingsUveso_0156="Anzeige ist aus"
aisettingsUveso_0185="Wegfindung"
aisettingsUveso_0186="Zeigt Wegfindung für alle Ebenen"
aisettingsUveso_0157="Weg und Standorte"
aisettingsUveso_0158="Zeigt Wegfindung und Standort Radien"
aisettingsUveso_0209="Weg und IMap-Gefahr"
aisettingsUveso_0210="Zeigt Wegfindung und Gefahrenzonen der ingame IMap"
aisettingsUveso_0159="Pfade und Land Marker"
aisettingsUveso_0160="Zeigt Wegfindung, Land Wegpunkte und Pfade"
aisettingsUveso_0161="Pfade und Wasser Marker"
aisettingsUveso_0162="Zeigt Wegfindung, Wasser Wegpunkte und Pfade"
aisettingsUveso_0163="Pfade und amphibische Marker"
aisettingsUveso_0164="Zeigt Wegfindung, amphibische Wegpunkte und Pfade"
aisettingsUveso_0231="Pfade und Hover Marker"
aisettingsUveso_0232="Zeigt Wegfindung, Hover Wegpunkte und Pfade"
aisettingsUveso_0165="Pfade und Lufraum Marker"
aisettingsUveso_0166="Zeigt Wegfindung, Lufraum Wegpunkte und Pfade"

aisettingsUveso_0167="DEBUG: KI Platoon Namen"
aisettingsUveso_0168="Zeigt Platoon und KI Plan Namen"
aisettingsUveso_0169="Anzeige is aus"
aisettingsUveso_0170="KI Uveso Namen"
aisettingsUveso_0171="Zeigt Platoon und KI Plan für KI Uveso"
aisettingsUveso_0206="KI RNG Namen"
aisettingsUveso_0207="Zeigt Platoon und KI Plan für KI RNG"
aisettingsUveso_0219="KI NutCracker Namen"
aisettingsUveso_0220="Zeigt Platoon und KI Plan für KI NutCracker"
aisettingsUveso_0216="KI Swarm Namen"
aisettingsUveso_0217="Zeigt Platoon und KI Plan für KI Swarm"
aisettingsUveso_0172="KI Dilli Namen"
aisettingsUveso_0173="Zeigt Platoon und KI Plan für KI Dilli"
aisettingsUveso_0174="KI Sorian Namen"
aisettingsUveso_0175="Zeigt Platoon und KI Plan für KI Sorian"
aisettingsUveso_0226="KI SCTA Namen"
aisettingsUveso_0227="Zeigt Platoon und KI Plan für KI SCTA"
aisettingsUveso_0176="Alle KI's"
aisettingsUveso_0177="Zeigt Platoon und KI Plan für alle KI's"

aisettingsUveso_0178="DEBUG: KI BuilderManager"
aisettingsUveso_0179="Druckt Platoon Builder Namen in das game.log"
aisettingsUveso_0180="Logging ist aus"
aisettingsUveso_0181="Log Builder für KI Uveso"
aisettingsUveso_0208="Log Builder für KI RNG"
aisettingsUveso_0221="Log Builder für KI NutCracker"
aisettingsUveso_0182="Log Builder für KI Dilli"
aisettingsUveso_0218="Log Builder für KI Swarm"
aisettingsUveso_0183="Log Builder für KI Sorian"
aisettingsUveso_0228="Log builder für KI SCTA"
aisettingsUveso_0184="Log Builder für alle KI's"

aisettingsUveso_0211="DEBUG: Unendlich Spiel"
aisettingsUveso_0212="Ausführung des Spiels in einer Endlosschleife für Langzeittests"
aisettingsUveso_0213="An"
aisettingsUveso_0214="Endlosschleife aus"
aisettingsUveso_0215="Endlosschleife an"

aisettingsUveso_0187="KI Einheitenlimit"
aisettingsUveso_0188="Einheitenlimit für KI; Unabhängig vom Limit für Spieler"
aisettingsUveso_0189="Es dürfen pro KI %d Einheiten im Spiel sein"
aisettingsUveso_0190="Gleiches Limit wie Spieler"
aisettingsUveso_0191="KI nutzt das gleiches Einheitenlimit wie für Spieler."

aisettingsUveso_0192="KI Map Marker Generator"
aisettingsUveso_0193="Automatisch generierte Map Marker für KI Wegfindung auf 5x5 und 10x10 Karten"
aisettingsUveso_0194="Originale Map Marker"
aisettingsUveso_0195="Benutzt Map Marker die vom Karten Autor erstellt wurden"
aisettingsUveso_0196="Automatisch wenn benötigt"
aisettingsUveso_0197="Automatisch generierte Map Marker für Karten ohne Marker"
aisettingsUveso_0198="Immer generieren"
aisettingsUveso_0199="Generiert immer Map Marker (Überschreibt vorhandene Marker)"
aisettingsUveso_0200="Keine Marker"
aisettingsUveso_0201="Benutzt die c-engine für Wegfindung (20%% langsamer)"
aisettingsUveso_0202="Drucke Marker ins game.log"
aisettingsUveso_0203="Druckt die Marker MasterChain Tabelle zum Ausschneiden & Einfügen in das game.log"

aisettingsUveso_0222="KIx Brecher Cheat Erhöhung"
aisettingsUveso_0223="Stellt die Erhöhung des Cheat-Multiplikators für die KIx Brecher ein. Der Multiplikator wird mit diesem Wert jede Minute erhöht"
aisettingsUveso_0224="KIx Brecher Erhöhungs Startzeit"
aisettingsUveso_0225="Stellt die Verzögerung in Minuten ein, bevor die KIx Brecher beginnt, den Cheat-Multiplikator zu erhöhen"

aisettingsUveso_0229="KI Spielbeender Startzeit"
aisettingsUveso_0230="Verzögerung in Minuten bis die KI anfängt Spielbeender zu bauen"
