
Uveso_0001="KI: Uveso Adaptiv"
Uveso_0002="Eine ausbalancierte KI. Gut für 5x5, 10x10 und 20x20 Karten."
Uveso_0003="KIx: Uveso Adaptiv"
Uveso_0004="Eine ausbalancierte KI, Einstellbar über Cheat-Optionen. Gut für 5x5, 10x10 und 20x20 Karten."

Uveso_0005="KI: Uveso Sturm"
Uveso_0006="Eine Sturm KI. Gut für 5x5 und 10x10 Karten."
Uveso_0007="KIx: Uveso Sturm"
Uveso_0008="Eine Sturm KI, Einstellbar über Cheat-Optionen. Gut für 5x5 und 10x10 Karten."

Uveso_0019="KI: Uveso Swarm"
Uveso_0020="Eine KI die massenweise Einheiten produziert. Gut für 5x5 und 10x10 Karten."
Uveso_0021="KIx: Uveso Swarm"
Uveso_0022="Eine KI die massenweise Einheiten produziert, Einstellbar über Cheat-Optionen. Gut für 5x5 und 10x10 Karten."

Uveso_0009="KI: Uveso Experimentals"
Uveso_0010="Eine KI die auf Experimentals fokussiert ist. Gut für 10x10 und 20x20 Karten."
Uveso_0011="KIx: Uveso Experimentals"
Uveso_0012="Eine KI die auf Experimentals fokussiert ist, Einstellbar über Cheat-Optionen. Gut für 10x10 und 20x20 Karten."

Uveso_0017="AIx: Uveso Brecher"
Uveso_0018="Eine KI die ab der 35. mit variablen Baugeschwindikeiten arbeitet, Einstellbar über Cheat-Optionen. Gut für 5x5, 10x10 und 20x20 maps."

Uveso_0013="KI: Uveso Einfach"
Uveso_0014="Eine einfache KI. Gut für 5x5, 10x10 und 20x20 Karten"
Uveso_0015="KIx: Uveso Einfach"
Uveso_0016="Eine einfache KI, Einstellbar über Cheat-Optionen. Gut für 5x5, 10x10 und 20x20 Karten"

aisettings_0153="DEBUG: KI Wegfindung"
aisettings_0154="Zeigt Wegfindung, Wegpunkte und Standort Radien (nur KI-Uveso)"
aisettings_0155="Aus"
aisettings_0156="Anzeige ist aus"
aisettings_0185="Wegfindung"
aisettings_0186="Zeigt Wegfindung für alle Ebenen"
aisettings_0157="Wegfindung und Standorte"
aisettings_0158="Zeigt Wegfindung und Standort Radien"
aisettings_0159="Pfade und Land Marker"
aisettings_0160="Zeigt Wegfindung, Land Wegpunkte und Pfade"
aisettings_0161="Pfade und Wasser Marker"
aisettings_0162="Zeigt Wegfindung, Wasser Wegpunkte und Pfade"
aisettings_0163="Pfade und amphibische Marker"
aisettings_0164="Zeigt Wegfindung, amphibische Wegpunkte und Pfade"
aisettings_0165="Pfade und Lufraum Marker"
aisettings_0166="Zeigt Wegfindung, Lufraum Wegpunkte und Pfade"

aisettings_0167="DEBUG: KI Platoon Namen"
aisettings_0168="Zeigt Platoon und KI Plan Namen"
aisettings_0169="Anzeige is aus"
aisettings_0170="KI Uveso Namen"
aisettings_0171="Zeigt Platoon und KI Plan für KI Uveso"
aisettings_0172="KI Dilli Namen"
aisettings_0173="Zeigt Platoon und KI Plan für KI Dilli"
aisettings_0174="KI Sorian Namen"
aisettings_0175="Zeigt Platoon und KI Plan für KI Sorian"
aisettings_0176="Alle KI's"
aisettings_0177="Zeigt Platoon und KI Plan für alle KI's"

aisettings_0178="DEBUG: KI BuilderManager"
aisettings_0179="Druckt Platoon Builder Namen in das game.log"
aisettings_0180="Logging ist aus"
aisettings_0181="Log Builder für KI Uveso"
aisettings_0182="Log Builder für KI Dilli"
aisettings_0183="Log Builder für KI Sorian"
aisettings_0184="Log Builder für alle KI's"

aisettings_0187="KI Einheitenlimit"
aisettings_0188="Einheitenlimit für KI; Unabhängig vom Limit für Spieler"
aisettings_0189="Es dürfen pro KI %d Einheiten im Spiel sein"
aisettings_0190="Gleiches Limit wie für Spieler"
aisettings_0191="KI nutzt das gleiches Einheitenlimit wie für Spieler."

aisettings_0192="KI Map Marker Generator"
aisettings_0193="Automatisch generierte Map Marker für KI Wegfindung auf 5x5 und 10x10 Karten"
aisettings_0194="Originale Map Marker"
aisettings_0195="Benutzt Map Marker die vom Karten Autor erstellt wurden"
aisettings_0196="Automatisch wenn benötigt"
aisettings_0197="Automatisch generierte Map Marker für Karten ohne Marker"
aisettings_0198="Immer generieren"
aisettings_0199="Generiert immer Map Marker (Überschreibt vorhandene Marker)"
aisettings_0200="Keine Marker"
aisettings_0201="Benutzt die c-engine für Wegfindung (20%% langsamer)"
aisettings_0202="Drucke Marker ins game.log"
aisettings_0203="Druckt die Marker MasterChain Tabelle zum Ausschneiden & Einfügen in das game.log"
